version: "3"

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: blog_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
  backend:
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - db

