name: Django CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
        pip install docker-compose

    - name: Build Docker Image
      run: docker-compose build

    - name: Run Docker Compose
      run: docker-compose up -d

    - name: Run Tests
      run: docker-compose run web python manage.py test

    - name: Tear Down Docker Compose
      run: docker-compose down

    - name: Post Test Cleanup
      if: always()
      run: docker-compose down -v
